ADD a SQL audit tool
shlomi-noach/awesome-mysql pull request #105
Opened 2022-06-29 02:45 UTC by sjjian

SQLE is a SQL audit platform for DBA or developer. 
docs: https://github.com/actiontech/sqle/blob/main/README_en.md

2022-07-17 07:55 UTC, shlomi-noach reviewed
Looks OK - a couple nits:

- GitHub README has link to enterprise edition; not a deal breaker
- How do you feel about adding a clear link to the English README.md file inside the main README.md file?

2024-06-03 06:34 UTC, dveeden requested changes
I think we should link to the English README

2024-06-03 06:35 UTC, dveeden commented on README.md
> +- [SQLE](https://github.com/actiontech/sqle) - SQLE is a SQL audit platform for DBA or developer
```suggestion
- [SQLE](https://github.com/actiontech/sqle/blob/main/README_en.md) - SQLE is a SQL audit platform for DBA or developer
```

2024-06-03 07:10 UTC, dveeden approved these changes

2024-06-03 07:21 UTC, shlomi-noach commented
@dveeden feel free to merge PRs which you approve.

2024-06-03 07:21 UTC, merged